version: "3"

services:
  web:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
    volumes:
      - .:/app
    ports:
      - "8000:5000"
    command: /app/bin/start.sh
    environment:
      - DJANGO_DEBUG=true
      - DJANGO_SECRET_KEY=not-secret-in-dev
