# Generated by Django 2.2.15 on 2020-08-23 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularyproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mpr.Product'),
            preserve_default=False,
        ),
    ]
