# Generated by Django 2.2.15 on 2020-08-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0002_formularyproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulary',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
