# Generated by Django 2.2.15 on 2020-08-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0006_auto_20200824_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nappi_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
